notifications:
  email: false
git:
  depth: false
  quiet: true
env:
  global:
  - TERM=dumb
language: java
jdk: openjdk8
node_js: lts/*
#services:
#- docker
#- xvfb
addons:
  apt:
    packages:
    - jq
    - bash
    - curl
#    - tree
#    - docker-ce
    - python-pip
#    - libxml2-utils
#    - libappindicator1
#    - fonts-liberation
#    - google-chrome-stable
install: true
before_install:
#- export CHROME_BIN=/usr/bin/google-chrome
#- export DISPLAY=:99.0
- nvm install lts/*
#- sudo add-apt-repository universe -y
#- sudo apt-get update -yqq
- sudo pip install --upgrade pip >/dev/null
- sudo $(which pip) install --upgrade httpie >/dev/null
#- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80
stages:
- test
- deploy
jobs:
  include:
  - stage: test
    name: ktor-html-css-example
    jdk: openjdk8
    script:
    - ./gradlew -b ./ktor-html-css-example/build.gradle.kts --refresh-dependencies
    - bash ktor-html-css-example/build/install/ktor-html-css-example/bin/ktor-html-css-example &
    - wait_for 8080
    - http :8080
    - http :8080/html-dsl/
    - http :8080/styles.css
    - http :8080/ktor/application/shutdown
    - stop_any 80 8080
  - stage: deploy
    node_js: lts/*
    name: npm deployment
    script: skip
    #if: branch = "master" AND type NOT IN (pull_request)
    before_deploy:
    #- if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ".$TRAVIS_BRANCH" != ".master" ] ; then exit 0 ; fi
    - env
    - set -e
    - npm i
    - npm run gh-pages
    env:
    - secure: "pVnY3pW/uKLUCaoktHk7DocHv7kusK7eYqonUGlPcmTfaX/m0CO7Xi4Msr3TjvCpJiscxEBSDqZZrpqBMWS7wr+niIHtHa8UkkS6DaG223JbuQKShTDErzIq+PuGs+wZ+jwSj2ET6FaV+Xy/6kG4ClflOourruukOlUqCVdH2cyxo6Y/sX7cjAv7BhTNpwt3xS2OleBQ1z0mcMPsLaCUsWFiPdZVlysowU3lJW3u+EQu6DOSp+wukyu3BrfT2xB5ZzVCqW2V9uzvyl8pB3/Oeb1Q5gai8B0CbUkRKTBrN+X0kbKp4zylDMRCz5gjG8hRthY/RN5QIwnVLmdG2AN6L1wwGLXCpRO3iHkrzAABnoCWLxkwwzgVVBMFfZdi1a6XKVsy4bceR0EnemAY6BwkvE/2Rqr+DuzrwMzNgY7xrsVWA/nAT2XCX/QouZ5qHKAXXWcSUsJfYO/eBGMemcHi+0nltgVL9ljizJBlbge/rxPMUmMF+2L38JMvXG+rIVs72yqm1W9sqGF8owXXpIo9zIybtkHC/evM7gLALXPRgwsIrl12PQXZjOB0ghbzSiQc+nE8kYsdoc8w2IceQZ/hSPUhvth5fY/mXAbE/7DwvDmQChD4I3iMKd3zGLhR6cYgWQ8QkSoDD3Cy190vcvWxOBGVHQIGCJchA1JBH3PISmg="
    deploy: &pages
      provider: pages
      github-token: "$GITHUB_TOKEN"
      local-dir: .vuepress/dist
      target_branch: gh-pages
      skip_cleanup: true
      keep-history: true
      on:
        branch: master
        condition: "$TRAVIS_PULL_REQUEST = false"
before_cache:
- for item in $(find ~/.gradle -name "*.lock") ;
    do sudo rm -rf $item ;
  done
cache:
  npm: true
  pip: true
  packages: true
  directories:
  - ~/.m2
  - ~/.gradle
  - ~/.docker
  - ./node_modules
